version: "2.2"
services:
  influxdb:
    container_name: influxdb2
    image: "influxdb:2.6.1"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "signalk"
      DOCKER_INFLUXDB_INIT_PASSWORD: "klangisklangis"
      DOCKER_INFLUXDB_INIT_ORG: "signalk_org"
      DOCKER_INFLUXDB_INIT_BUCKET: "signalk_bucket"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "signalk_token"
    volumes:
      - "./docker-data/influx:/var/lib/influxdb2"
      - "./docker-data/influx/config:/etc/influxdb2"
    ports:
      - "8086:8086"
    restart: always
    user: "1000"
    mem_limit: 300m
  grafana:
    container_name: grafana
    image: "grafana/grafana:10.2.6"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "signalk-datasource,signalk-trackmap"
    ports:
      - "3001:3000"
    volumes:
      - "./:/etc/grafana/provisioning/datasources"
      - "./dashboards:/etc/grafana/provisioning/dashboards"
      - "/var/lib/grafana/plugins/"
      - "./trackmap_g10/dist/:/var/lib/grafana/plugins/signalk-trackmap"
      - "./datasource_g10/dist/:/var/lib/grafana/plugins/signalk-datasource"
      - "./docker-data/grafana:/var/lib/grafana"
    restart: always
    user: "1000"
    mem_limit: 200m
