services:
  grafana:
    user: root
    container_name: 'signalk-signalk-datasource'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.2.0}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3001:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/signalk-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/signalk-signalk-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.signalk-signalk-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: signalk-signalk-datasource
