name: Build modules and Docker container

on:
  push:
    branches:
    - master
    - "build-docker"

jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Build trackmap
        run: |
          cd trackmap
          npm install
          npm run build

      - name: Build datasource
        run: |
          cd datasource
          npm install
          npm run build

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: tkurki/signalk-grafana
          tag-sha: true # add git short SHA as Docker tag
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: tkurki
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
