on:
  push:
    tags:
      - 'plugin_*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: trackmap

    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run build --if-present
      - run: mv dist tkurki-trackmap
      - name: Create zip file
        uses: thedoctor0/zip-release@master
        with:
          path: 'tkurki-trackmap/'
          filename: tkurki-trackmap-${{ steps.vars.outputs.tag }}.zip
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
