on:
  push:
    tags:
      - 'trackmap_*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: trackmap

    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run build --if-present
      - run: mv dist signalk-trackmap
      - run: zip -r signalk-trackmap-${{ steps.vars.outputs.tag }}.zip signalk-trackmap
      - run: ls
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: trackmap/signalk-trackmap-${{ steps.vars.outputs.tag }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}

# git tag -d plugin_v0.0.1 && git tag plugin_v0.0.1 && git push --delete origin plugin_v0.0.1 && git push --tags